Feature/browse issues
sokqa/Jira-Testing-Project-Norse-Manon-Salad pull request #4
Opened 2019-03-21 15:36 UTC by deaack

All the tests run successfully if enough timeout(10s) and maximal attempt(10) are set as environment variables.
I created the BrowseIssues and BrowseIssuesTest classes and added a similar function Feature class on waiting to be clickable(forgot to add "attempts" as variable, burnt int 2 value).
Did not feel the urge to read data from CSV file as i worked with very little inputs, found it confusing without consultation.
Most of the functions print actual result.

2019-03-22 06:08 UTC, sokqa reviewed
Hey, thanks for your pull request.
Generally, I find your logic unusual and often hard to understand so I think we could sit down together and go through you code.

2019-03-22 06:15 UTC, sokqa requested changes
- I think your 'all projects have at least 3 issues' and 'all issue details appear' tests fail because of the lack of some waitings so this should be addressed.
- I find the xpath of the 'numberOfIssues' web element unnecessarily long and unreadable. That element can be found in a much simpler way, for example using a css selector.

2019-04-01 12:53 UTC, bencebachraty requested changes
Thank you for the changes, Bence!
A few things I noticed:
- I think the xpath of the 'numberOfIssues' webelement could be shorter so it's more flexible and readable

- The testPagination test throws an exception every time I run it even with the timeout and max attempts set to the value given in the pull request comment:
unknown error : Element < span class="aui-icon aui-icon-small aui-iconfont-chevron-right">...< /span> is not clickable at point (494, 504). Other element would receive the click: < div class="loading">< /div> 

- Both BrowseIssues and BrowseIssuesTest has a Login object when only one is necessary

- The getNumOfIssuesByPagination method in BrowseIssues has multiple waits after one another without having any action between them, which seems unnecessary to me

2019-04-02 08:54 UTC, sokqa approved these changes

2019-04-02 08:55 UTC, bencebachraty approved these changes

2019-04-02 08:55 UTC, merged